# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [52]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

import matplotlib.pylab as plt
import seaborn as sns

from sklearn import datasets
from sklearn.model_selection import train_test_split

from sklearn import linear_model
from sklearn.linear_model import LinearRegression

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix


from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

## Regression Model Evaluation

In [2]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [4]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [ ]:
# Your code here :
X_data = data.drop('MEDV', axis=1)
y_data = data['MEDV']

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.2, random_state=42)
features = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']


## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [ ]:
# Your code here :

lr = LinearRegression()
lr.fit(X_train, y_train)

#Regression coefs
coefs_lr = pd.Series(np.abs(lr.coef_), features).sort_values()


#Prediction
y_test_pred = lr.predict(X_test)



Intercept and coefs:
30.24675099392349 [-1.13055924e-01  3.01104641e-02  4.03807204e-02  2.78443820e+00
 -1.72026334e+01  4.43883520e+00 -6.29636221e-03 -1.44786537e+00
  2.62429736e-01 -1.06467863e-02 -9.15456240e-01  1.23513347e-02
 -5.08571424e-01]

MSE:24.291119474973538
R^2 Score: 0.7508856358979673
R^2 Score:0.6687594935356317


## 3. Calculate and print R-squared for both the training and the testing set.

In [ ]:
# Your code here :

# Evaluation
r2score_train = lr.score(X_train, y_train)
r2score_test = lr.score(X_test, y_test)
# The coefficients
print('\nIntercept and coefs:\n{} {}'.format(lr.intercept_, lr.coef_))

# Coefficient of determination (1= perfect prediction)
print('R^2 Score: {}'.format(r2score_train))
print('R^2 Score:{}'.format(r2score_test))


Intercept and coefs:
30.24675099392349 [-1.13055924e-01  3.01104641e-02  4.03807204e-02  2.78443820e+00
 -1.72026334e+01  4.43883520e+00 -6.29636221e-03 -1.44786537e+00
  2.62429736e-01 -1.06467863e-02 -9.15456240e-01  1.23513347e-02
 -5.08571424e-01]

MSE:24.291119474973538
R^2 Score: 0.7508856358979673
R^2 Score:0.6687594935356317


## 4. Calculate and print mean squared error for both the training and the testing set.

In [17]:
# Your code here :

# Evaluation
mse = mean_squared_error(y_test, y_test_pred)

# Mean Squared Error (MSE)
print('\nMSE:{}'.format(mse))



MSE:24.291119474973538


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [20]:
# Your code here :
mae = mean_absolute_error(y_test, y_test_pred)

print("Mean Absolute Error:", mae)

Mean Absolute Error: 3.1890919658878416


## Classification Model Evaluation

In [21]:
from sklearn.datasets import load_iris
data = load_iris()

In [22]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [23]:
column_names = data.feature_names

In [24]:
df = pd.DataFrame(data['data'],columns=column_names)

In [25]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [26]:
target = pd.DataFrame(data.target)

In [27]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [28]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [31]:
# Your code here :
X = data['data'] # features
y = data['target'] # target variable

# 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [42]:
# Your code here :

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# Creating & training the model
lr = LogisticRegression()
lr.fit(X_train, y_train)

# Predictions
y_train_pred = lr.predict(X_train)
y_test_pred = lr.predict(X_test)

# Evaluating results
print("==== Training Set ====")
print(classification_report(y_train, y_train_pred))
print("Confusion Matrix:\n", confusion_matrix(y_train, y_train_pred))

print("\n==== Testing Set ====")
print(classification_report(y_test, y_test_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))


lr.fit(X_train_scaled, y_train)
y_pred = lr.predict(X_test_scaled)
print("Logistic Regression Report:\n", classification_report(y_test, y_pred))



# High accuracy.


==== Training Set ====
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      0.93      0.96        41
           2       0.93      1.00      0.96        39

    accuracy                           0.97       120
   macro avg       0.98      0.98      0.97       120
weighted avg       0.98      0.97      0.97       120

Confusion Matrix:
 [[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]

==== Testing Set ====
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Logistic Regression Report:
               precision    recall  f1-score   suppo

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [ ]:
# Your code here :

# Train accuracy
train_accuracy = accuracy_score(y_train, y_train_pred)
print(f"Training Accuracy: {train_accuracy:.2f}")

# Test accuracy
test_accuracy = accuracy_score(y_test, y_test_pred)
print(f"Testing Accuracy: {test_accuracy:.2f}")

# Training Accuracy: 0.97
# Testing Accuracy: 1.00

Training Accuracy: 0.97
Testing Accuracy: 1.00


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [ ]:
# Your code here :

# Training BAS
train_bal_acc = balanced_accuracy_score(y_train, y_train_pred)
print(f"Training Balanced Accuracy: {train_bal_acc:.2f}")

# Testing BAS
test_bal_acc = balanced_accuracy_score(y_test, y_test_pred)
print(f"Testing Balanced Accuracy: {test_bal_acc:.2f}")

# Training Balanced Accuracy: 0.98
# Testing Balanced Accuracy: 1.00

Training Balanced Accuracy: 0.98
Testing Balanced Accuracy: 1.00


## 10. Calculate and print the precision score for both the training and the testing set.

In [ ]:
# Your code here :

train_prec_score = precision_score(y_train, y_train_pred, average='macro')
print(f'Training Precision Score:{train_prec_score:.2f}')


test_prec_score = precision_score(y_test, y_test_pred, average='macro')
print(f'Testing Precision Score: {test_prec_score:.2f}')


# Training Precision Score:0.98
# Testing Precision Score: 1.00

Training Precision Score:0.98
Testing Precision Score: 1.00


## 11. Calculate and print the recall score for both the training and the testing set.

In [ ]:
# Your code here :
train_recall_score = recall_score(y_train, y_train_pred, average='macro')
print(f'Training Recall Score:{train_prec_score:.2f}')


test_recall_score = recall_score(y_test, y_test_pred, average='macro')
print(f'Testing Recall Score: {test_prec_score:.2f}')

# Training Recall Score:0.98
# Testing Recall Score: 1.00

Training Recall Score:0.98
Testing Recall Score: 1.00


## 12. Calculate and print the F1 score for both the training and the testing set.

In [ ]:
# Your code here :

train_f1_score = f1_score(y_train, y_train_pred, average='macro')
print(f'F1 Score:{train_f1_score:.2f}')


test_f1_score = f1_score(y_test, y_test_pred, average='macro')
print(f'F1 Score: {test_f1_score:.2f}')

# F1 Score:0.97
# F1 Score: 1.00

F1 Score:0.97
F1 Score: 1.00


## 13. Generate confusion matrices for both the training and the testing set.

In [56]:
# Your code here :
train_cm = confusion_matrix(y_test, y_pred)
print("Train Confusion Matrix:\n", train_cm)

test_cm = confusion_matrix(y_test, y_test_pred)
print("Test Confusion Matrix\n", test_cm)

'''Train Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Test Confusion Matrix
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]'''


Train Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Test Confusion Matrix
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


'Train Confusion Matrix:\n [[10  0  0]\n [ 0  9  0]\n [ 0  0 11]]\nTest Confusion Matrix\n [[10  0  0]\n [ 0  9  0]\n [ 0  0 11]]'

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [26]:
# Have fun here !